name: get_localization
description: Localize your app easily entirely in flutter using dart getters. No need for code generation.
version: 3.0.0
homepage: https://github.com/bdlukaa/get_localization

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4
